<a href="https://colab.research.google.com/github/rOluochKe/learning-ds-ml/blob/main/Learning_DS_and_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Chapter One:** Environment Setup

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


**Chapter Two:** Python Crash Course

In [ ]:
### Variables and data types
first_name = "Joseph"
print(type(first_name))

age = 35
print(type(age))

weight = 75.04
print(type(weight))

married = False
print(type(married))

cars = ["audi", "benz", "jeep"]
print(type(cars))

days = ("Mon", "Tue", "Wed", "Thurs", "Fri")
print(type(days))

shopping_items = {1: "bread", 2: "milk", 3: "sugar"}
print(type(shopping_items))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'list'>
<class 'tuple'>
<class 'dict'>


In [ ]:
### Arithetic operators
x = 20
y = 15
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x % y)
print(x ** y)

35
5
300
1.3333333333333333
5
32768000000000000000


In [ ]:
### Logical operators
### AND, and, OR, or, NOT, not
# (a and b) = False, (a and a) = True
# (a or b) = True
# not(a and b) = True

X = True
Y = False
print(X and Y)
print(X or Y)
print(not(X and Y))

False
True
True


In [ ]:
### Comparison operators
X = 20
Y = 35
print(X == Y)
print(X != Y)
print(X > Y)
print(X < Y)
print(X >= Y)
print(X <= Y)

False
True
False
True
False
True


In [ ]:
### Assignment Operators
# Assignment =
# Divide and assign /=
# Take modulus and assign %=
# Take exponent and assign
X = 20; Y = 10
R = X + Y
print (R)

X = 20;
Y = 10
X += Y
print (X)

X = 20;
Y = 10
X -= Y
print (X)

X = 20;
Y = 10
X *= Y
print (X)

X = 20;
Y = 10
X /= Y
print (X)

X = 20;
Y = 10
X %= Y
print (X)

X = 20;
Y = 10
X **= Y
print (X)

30
30
10
200
2.0
0
10240000000000


In [ ]:
### Membership operator
# in operator
# not in operator

days = ("Sunday" , "Monday" , "Tuesday" , "Wednesday" , "Thursday" , "Friday" , "Saturday")
print ("Sunday" in days)

print ("Xunday" not in days)

True
True


In [ ]:
### Conditional statements
if 10 > 5:
  print("Ten is greater than 10")

if 5 > 10:
  print("5 is greater than 10")
else:
  print("10 is greater than 5")

if 5 > 10:
  print("5 is greater than 10")
elif 8 < 4:
  print("8 is smaller than 4")
else:
  print("5 is not greater than 10 and 8 is not smaller than 4")

Ten is greater than 10
10 is greater than 5
5 is not greater than 10 and 8 is not smaller than 4


In [ ]:
### Iteration statements
print("for loop")
items = range(5)
for item in items:
  print(item)
print("while loop")
c = 0
while c < 10:
  print(c)
  c = c +1

for loop
0
1
2
3
4
while loop
0
1
2
3
4
5
6
7
8
9


In [ ]:
### Functions
def myfuncparam(num):
  print('This is a function with parameter value: ' + num)

### function call
myfuncparam('Parameter 1')

This is a function with parameter value: Parameter 1


In [ ]:
### Objects and Classes
class Fruit:
  name = "apple"
  price = 10

  def eat_fruit(self):
    print("Fruit has been eaten")

f = Fruit()
f.eat_fruit()
print(f.name)
print(f.price)

### Contructor
print('constructor ===============')
class Fruit:
  name = "apple"
  price = 10

  def __init__(self, fruit_name, fruit_price):
    Fruit.name = fruit_name
    Fruit.price = fruit_price

  def eat_fruit(self):
    print("Fruit has been eaten")

f = Fruit("orange", 15)
f.eat_fruit()
print(f.name)
print(f.price)

Fruit has been eaten
apple
10
constructor ===============
Fruit has been eaten
orange
15


* NumPy: is one of the most commonly used libraries for numeric and scientific computing.
* Matplotlib: is the de facto standard for static data visualization in Python, which is the first step in data science and machine learning.
* Seaborn: library is built on top of the Matplotlib library and contains all the plotting capabilities of Matplotlib. However, with Seaborn, you can plot much more pleasing and aesthetic graphs with the help of Seaborn default styles and color palettes.
* Pandas: like Seaborn, is based on the Matplotlib library and offers utilities that can be used to plot different types of static plots in a single line of codes. With Pandas, you can import data in various formats such as CSV (Comma Separated View) and TSV (Tab Separated View) and can plot a variety of data visualizations
via these data sources.
* Scikit Learn, also called sklearn: is an extremely useful library for data science and machine learning in Python. Sklearn contains many built-in modules that can be used to perform data preparation tasks such as feature engineering, feature scaling, outlier detection, discretization, etc.
* TensorFlow: is one of the most frequently used libraries for deep learning. TensorFlow has been developed by Google and offers an easy to use API for the development of various deep learning models.
* Keras: is a high-level TensorFlow library that implements complex TensorFlow functionalities under the hood. If you are a newbie to deep learning, Keras is the one deep learning library that you should start for developing deep learning library.Keras is a high-level TensorFlow library that implements complex TensorFlow functionalities under the hood. If you are a newbie to deep learning, Keras is the one deep learning library that you should start for developing deep learning library.

**Chapter Three:** NumPy Library for Data Analysis

In [1]:
pip install numpy

In [3]:
### NumPy array
import numpy as np
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
print(type(nums_array))
print(nums_array)

<class 'numpy.ndarray'>
[10 12 14 16 20]


In [4]:
### Multi-dimensional array
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
nums_2d.shape

(3, 3)

In [8]:
### arange()
nums_array = np.arange(5,11)
print(nums_array)

### steps
nums_arr = np.arange(5,12,2)
print(nums_arr)

[ 5  6  7  8  9 10]
[ 5  7  9 11]


In [12]:
### ones()
ones_array = np.ones(7)
print(ones_array)

### 2d array of ones()
ones_array = np.ones((6,4))
print(ones_array)

[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
### zeros()
zeros_array = np.zeros(6)
print(zeros_array)

### 2d array of zeros()
zeros_array = np.zeros((6,4))
print(zeros_array)

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
### eye()
eyes_array = np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
### random.rand()
uniform_random = np.random.rand(4, 5)
print(uniform_random)

### normal distribution
normal_random = np.random.randn(4, 5)
print(uniform_random)

[[0.30019395 0.335196   0.70906241 0.49776323 0.97300575]
 [0.16948037 0.15829095 0.81619506 0.56181618 0.93203116]
 [0.17319136 0.46812209 0.76312863 0.83233501 0.04797072]
 [0.72994683 0.1226909  0.28235066 0.82933295 0.67303025]]
[[0.30019395 0.335196   0.70906241 0.49776323 0.97300575]
 [0.16948037 0.15829095 0.81619506 0.56181618 0.93203116]
 [0.17319136 0.46812209 0.76312863 0.83233501 0.04797072]
 [0.72994683 0.1226909  0.28235066 0.82933295 0.67303025]]


In [20]:
### random.randint() - generate random ints between 10 - 50
integer_random = np.random.randint(10, 50, 5)
print(integer_random)

[20 23 13 23 16]


In [21]:
### reshape() - 4 x 6 = 24
uniform_random = np.random.rand(4, 6)
uniform_random = uniform_random.reshape(3, 8)
print(uniform_random)

[[0.74757965 0.9833532  0.86099487 0.63229644 0.80653102 0.68024935
  0.53986563 0.98840562]
 [0.83383323 0.2917367  0.20733558 0.09114874 0.77094259 0.67128858
  0.367726   0.57169791]
 [0.75505205 0.06119812 0.79866227 0.48289669 0.93924938 0.79592965
  0.24738396 0.51274092]]


In [25]:
### index
s = np.arange(1,11)
print(s)
print (s[1])

### slice
print(s[1:9])
print(s[:5])
print(s[5:])

[ 1  2  3  4  5  6  7  8  9 10]
2
[2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[ 6  7  8  9 10]


In [29]:
### 2d slicing
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[:2,:])

row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[:,:2])

row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[1:,1:])

[[10 12 13]
 [45 32 16]]
[[10 12]
 [45 32]
 [45 32]]
[[32 16]
 [32 16]]


In [30]:
### sqrt()
nums = [10,20,30,40,50]
np_sqr = np.sqrt(nums)
print(np_sqr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [31]:
### logs()
nums = [10,20,30,40,50]
np_log = np.log(nums)
print(np_log)

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [32]:
### exp()
nums = [10,20,30,40,50]
np_exp = np.exp(nums)
print(np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


In [33]:
### sin()
nums = [10,20,30,40,50]
np_sine = np.sin(nums)
print(np_sine)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]


In [34]:
### cos()
nums = [10,20,30,40,50]
np_cos = np.cos(nums)
print(np_cos)

[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


**NumPy for Linear Algebra Operations**

In [36]:
### dot() - To find a matrix dot product
A = np.random.randn(4,5)
B = np.random.randn(5,4)

Z = np.dot(A,B)
print(Z)

[[-3.16240491  2.53482099  3.11083839 -2.01485527]
 [ 0.25115458  1.82218092  2.46762733 -1.75486205]
 [-3.08325858  1.16087918  2.21818916  2.10042239]
 [-3.84859345  0.96269246  3.48963742  1.77761114]]


In [37]:
### multiply() - Finding the dot product of two matrices, you can element-wise multiply two matrices
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
multiply = np.multiply(nums_2d, nums_2d)
print(multiply)

[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


In [41]:
### inalg.inv() - find the inverse of a matrix
row1 = [1, 2, 3]
row2 = [4, 5, 6]
row3 = [7, 8, 9]

nums_2d = np.array([row1, row2, row3])

try:
    inverse = np.linalg.inv(nums_2d)
    print("Inverse matrix:")
    print(inverse)
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")

Matrix is singular and cannot be inverted.


In [42]:
### linalg.det() - determinant of a matrix
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

nums_2d = np.array([row1, row2, row3])
determinant = np.linalg.det(nums_2d)
print(determinant)

0.0


In [43]:
### trace() - the sum of all the elements along the diagonal of a matrix.
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

nums_2d = np.array([row1, row2, row3])
trace = np.trace(nums_2d)
print(trace)

15


**Chapter Four:** Pandas Library for Data Analysis

In [44]:
pip install pandas

In [52]:
import pandas as pd

In [53]:
### Upload data
from google.colab import files
uploaded = files.upload()

Saving titanic_data.csv to titanic_data.csv


In [54]:
titanic_data = pd.read_csv('titanic_data.csv')
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [55]:
### filter rows
titanic_pclass1= (titanic_data.Pclass == 1)
titanic_pclass1

0      False
1       True
2      False
3       True
4      False
       ...  
886    False
887     True
888    False
889     True
890    False
Name: Pclass, Length: 891, dtype: bool

In [56]:
titanic_pclass1= (titanic_data.Pclass == 1)
titanic_pclass1_data = titanic_data[titanic_pclass1]
titanic_pclass1_data.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
11           12         1       1   
23           24         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
23                       Sloper, Mr. William Thompson    male  28.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
11      0    113783  26.5500  C103        S  
23      0    113788  35.5000    A6        S

In [57]:
### comparison between the column values and filtering of rows
titanic_pclass_data = titanic_data[titanic_data.Pclass == 1]
titanic_pclass_data.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
11           12         1       1   
23           24         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
23                       Sloper, Mr. William Thompson    male  28.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
11      0    113783  26.5500  C103        S  
23      0    113788  35.5000    A6        S

In [59]:
### isin operator
ages = [20,21,22]
age_dataset = titanic_data[titanic_data["Age"].isin(ages)]
age_dataset.head()

PassengerId  Survived  Pclass                            Name     Sex  \
0             1         0       3         Braund, Mr. Owen Harris    male   
12           13         0       3  Saundercock, Mr. William Henry    male   
37           38         0       3        Cann, Mr. Ernest Charles    male   
51           52         0       3    Nosworthy, Mr. Richard Cater    male   
56           57         1       2               Rugg, Miss. Emily  female   

     Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
0   22.0      1      0   A/5 21171   7.25   NaN        S  
12  20.0      0      0   A/5. 2151   8.05   NaN        S  
37  21.0      0      0  A./5. 2152   8.05   NaN        S  
51  21.0      0      0  A/4. 39886   7.80   NaN        S  
56  21.0      0      0  C.A. 31026  10.50   NaN        S

In [60]:
### filter rows based on multiple conditions using logical and (&) and or (|) operators
ages = [20,21,22]
ageclass_dataset = titanic_data[titanic_data["Age"].isin(ages) & (titanic_data["Pclass"] == 1)]
ageclass_dataset.head()

PassengerId  Survived  Pclass                                Name  \
102          103         0       1           White, Mr. Richard Frasar   
151          152         1       1   Pears, Mrs. Thomas (Edith Wearne)   
356          357         1       1         Bowerman, Miss. Elsie Edith   
373          374         0       1                 Ringhini, Mr. Sante   
539          540         1       1  Frolicher, Miss. Hedwig Margaritha   

        Sex   Age  SibSp  Parch    Ticket      Fare Cabin Embarked  
102    male  21.0      0      1     35281   77.2875   D26        S  
151  female  22.0      1      0    113776   66.6000    C2        S  
356  female  22.0      0      1    113505   55.0000   E33        S  
373    male  22.0      0      0  PC 17760  135.6333   NaN        C  
539  female  22.0      0      2     13568   49.5000   B39        C

In [61]:
### filter() method
titanic_data_filter = titanic_data.filter(["Name" , "Sex" , "Age"])
titanic_data_filter.head()

Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [63]:
### drop() method and pass it the list of columns that you want to drop
titanic_data_filter = titanic_data.drop(["Name" , "Sex" , "Age"], axis = 1)
titanic_data_filter.head()

PassengerId  Survived  Pclass  SibSp  Parch            Ticket     Fare  \
0            1         0       3      1      0         A/5 21171   7.2500   
1            2         1       1      1      0          PC 17599  71.2833   
2            3         1       3      0      0  STON/O2. 3101282   7.9250   
3            4         1       1      1      0            113803  53.1000   
4            5         0       3      0      0            373450   8.0500   

  Cabin Embarked  
0   NaN        S  
1   C85        C  
2   NaN        S  
3  C123        S  
4   NaN        S

In [64]:
### Concatenating Dataframes
titanic_pclass1_data = titanic_data[titanic_data.Pclass == 1]
print(titanic_pclass1_data.shape)

titanic_pclass2_data = titanic_data[titanic_data.Pclass == 2]
print(titanic_pclass2_data.shape)

(216, 12)
(184, 12)


In [65]:
### append() method
final_data = titanic_pclass1_data.append(titanic_pclass2_data, ignore_index=True)
print(final_data.shape)

(400, 12)


<ipython-input-65-30d7e35225ec>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_data = titanic_pclass1_data.append(titanic_pclass2_data, ignore_index=True)


In [66]:
### concat() method
final_data = pd.concat([titanic_pclass1_data, titanic_pclass2_data])
print(final_data.shape)

(400, 12)


In [67]:
### concatenate dataframes horizontally
df1 = final_data[:200]
print(df1.shape)
df2 = final_data[200:]
print(df2.shape)

final_data2 = pd.concat([df1, df2], axis = 1, ignore_index = True)
print(final_data2.shape)

(200, 12)
(200, 12)
(400, 24)


In [68]:
### Sorting Dataframes
age_sorted_data = titanic_data.sort_values(by=['Age'])
age_sorted_data.head()

PassengerId  Survived  Pclass                             Name     Sex  \
803          804         1       3  Thomas, Master. Assad Alexander    male   
755          756         1       2        Hamalainen, Master. Viljo    male   
644          645         1       3           Baclini, Miss. Eugenie  female   
469          470         1       3    Baclini, Miss. Helene Barbara  female   
78            79         1       2    Caldwell, Master. Alden Gates    male   

      Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
803  0.42      0      1    2625   8.5167   NaN        C  
755  0.67      1      1  250649  14.5000   NaN        S  
644  0.75      2      1    2666  19.2583   NaN        C  
469  0.75      2      1    2666  19.2583   NaN        C  
78   0.83      0      2  248738  29.0000   NaN        S

In [69]:
### ascending
age_sorted_data = titanic_data.sort_values(by=['Age'], ascending = False)
age_sorted_data.head()

PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                   Svensson, Mr. Johan   
493          494         0       1               Artagaveytia, Mr. Ramon   
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   

      Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
630  male  80.0      0      0     27042  30.0000   A23        S  
851  male  74.0      0      0    347060   7.7750   NaN        S  
493  male  71.0      0      0  PC 17609  49.5042   NaN        C  
96   male  71.0      0      0  PC 17754  34.6542    A5        C  
116  male  70.5      0      0    370369   7.7500   NaN        Q

In [70]:
### by
age_sorted_data = titanic_data.sort_values(by=['Age','Fare'], ascending = False)
age_sorted_data.head()

PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                   Svensson, Mr. Johan   
493          494         0       1               Artagaveytia, Mr. Ramon   
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   

      Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
630  male  80.0      0      0     27042  30.0000   A23        S  
851  male  74.0      0      0    347060   7.7750   NaN        S  
493  male  71.0      0      0  PC 17609  49.5042   NaN        C  
96   male  71.0      0      0  PC 17754  34.6542    A5        C  
116  male  70.5      0      0    370369   7.7500   NaN        Q

In [72]:
### apply()
updated_class = titanic_data.Pclass.apply(lambda x : x + 2)
updated_class.head()

0    5
1    3
2    5
3    3
4    5
Name: Pclass, dtype: int64

In [73]:
### mult()
def mult(x):
  return x * 2

updated_class = titanic_data.Pclass.apply(mult)
updated_class.head()

0    6
1    2
2    6
3    2
4    6
Name: Pclass, dtype: int64

In [74]:
### Pivot & Crosstab
import matplotlib.pyplot as plt
import seaborn as sns

flights_data = sns.load_dataset('flights')

flights_data.head()

year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [75]:
flights_data_pivot =flights_data.pivot_table(index='month', columns='year', values='passengers')
flights_data_pivot.head()

year   1949  1950  1951  1952  1953  1954  1955  1956  1957  1958  1959  1960
month                                                                        
Jan     112   115   145   171   196   204   242   284   315   340   360   417
Feb     118   126   150   180   196   188   233   277   301   318   342   391
Mar     132   141   178   193   236   235   267   317   356   362   406   419
Apr     129   135   163   181   235   227   269   313   348   348   396   461
May     121   125   172   183   229   234   270   318   355   363   420   472

In [76]:
### crosstab()
pd.crosstab(titanic_data.Pclass, titanic_data.Age, margins=True)

Age     0.42  0.67  0.75  0.83  0.92  1.0  2.0  3.0  4.0  5.0  ...  63.0  \
Pclass                                                         ...         
1          0     0     0     0     1    0    1    0    1    0  ...     1   
2          0     1     0     2     0    2    2    3    2    1  ...     0   
3          1     0     2     0     0    5    7    3    7    3  ...     1   
All        1     1     2     2     1    7   10    6   10    4  ...     2   

Age     64.0  65.0  66.0  70.0  70.5  71.0  74.0  80.0  All  
Pclass                                                       
1          2     2     0     1     0     2     0     1  186  
2          0     0     1     1     0     0     0     0  173  
3          0     1     0     0     1     0     1     0  355  
All        2     3     1     2     1     2     1     1  714  

[4 rows x 89 columns]

In [77]:
### where
titanic_data.Fare = np.where( titanic_data.Age > 20, titanic_data.Fare +5, titanic_data.Fare)

titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171  12.2500   NaN        S  
1      0          PC 17599  76.2833   C85        C  
2      0  STON/O2. 3101282  12.9250   NaN        S  
3      0            113803  58.1000  C123        S  
4      0            373450  13.0500   NaN        S